"""add products product_units stock_movements tables

Revision ID: 3a7d393b8bc1
Revises: 437e0e89b31c
Create Date: 2026-09-14 11:04:11.676582

v0.7 slice 1 (roadmap.md "Inventory depth"), see docs/decisions.md.
Additive only: three new tables, no changes to any existing table.
`products` replaces canonicalize_product_name's string-only stopgap
(docs/decisions.md [2026-08-27]) as a real entity current stock can be
tracked against, resolved the same get-or-create way as v0.2's
customers/suppliers (app/entities.py's resolve_product). `stock_movements`
is an append-only ledger -- current stock is derived by summing it
(app/inventory.py's get_current_stock), never stored as a mutable field.
`product_units` lets a product declare non-base units (e.g. "carton" = 24
"piece") with a deterministic conversion factor.

No backfill: unlike the v0.2 customers/suppliers migration, this does not
retroactively create Product rows from existing sales.product_name /
inventory.product_name strings, and does not touch the existing
`inventory` table at all. Deliberate -- see roadmap.md v0.7's "Explicitly
NOT yet" (no automatic backfill/merge decision made yet); new write paths
adopt `products` in the next slice, old rows stay exactly as they are.

Autogenerate also picked up unrelated pre-existing drift between the
local dev DB and the models (a stray `refresh_tokens` table left over
from the Clerk migration, a document_extractions unique-constraint/index
ordering difference, and the embeddings HNSW index -- the last a known
autogenerate false positive per migration 54e302e6112e's docstring, since
it's created via raw SQL rather than a SQLAlchemy Index). None of that is
this migration's concern, so it's stripped out below; only the three new
tables remain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3a7d393b8bc1'
down_revision: Union[str, Sequence[str], None] = '437e0e89b31c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('base_unit', sa.String(), server_default='unit', nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=True),
    sa.Column('cost_price', sa.Numeric(), nullable=True),
    sa.Column('selling_price', sa.Numeric(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'normalized_name', name='uq_products_business_normalized_name')
    )
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    op.create_table('product_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('unit_name', sa.String(), nullable=False),
    sa.Column('conversion_to_base', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'unit_name', name='uq_product_units_product_unit_name')
    )
    op.create_index(op.f('ix_product_units_product_id'), 'product_units', ['product_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_business_id'), 'stock_movements', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    # ### end Alembic commands ### (unrelated autogenerate drift removed -- see docstring)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ### (unrelated autogenerate drift removed -- see docstring)
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_business_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_product_units_product_id'), table_name='product_units')
    op.drop_table('product_units')
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
