"""add insights table

Revision ID: 4117a68dbfe8
Revises: e3851ec73ac3
Create Date: 2026-07-24 16:53:51.835956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4117a68dbfe8'
down_revision: Union[str, Sequence[str], None] = 'e3851ec73ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id', 'fingerprint', name='uq_insights_business_fingerprint')
    )
    op.create_index(op.f('ix_insights_business_id'), 'insights', ['business_id'], unique=False)
    op.create_index(op.f('ix_insights_fingerprint'), 'insights', ['fingerprint'], unique=False)
    # NOTE: autogenerate also detected drift on document_extractions/embeddings
    # indexes unrelated to this change (pre-existing model/DB mismatch, not
    # introduced here) -- deliberately not included; this migration only adds
    # the insights table, per the additive-migration rule.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_fingerprint'), table_name='insights')
    op.drop_index(op.f('ix_insights_business_id'), table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###
