"""add business_facts table

Revision ID: 6930a3469643
Revises: 4117a68dbfe8
Create Date: 2026-07-24 17:52:56.952184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6930a3469643'
down_revision: Union[str, Sequence[str], None] = '4117a68dbfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_facts_business_id'), 'business_facts', ['business_id'], unique=False)
    # NOTE: autogenerate also detected drift on document_extractions/embeddings
    # indexes unrelated to this change (pre-existing model/DB mismatch, not
    # introduced here) -- deliberately not included; this migration only adds
    # the business_facts table, per the additive-migration rule.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_facts_business_id'), table_name='business_facts')
    op.drop_table('business_facts')
    # ### end Alembic commands ###
