"""add pending entries table

Revision ID: 6cee3eac28bd
Revises: e24216de8f9c
Create Date: 2026-08-07 13:57:01.785342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cee3eac28bd'
down_revision: Union[str, Sequence[str], None] = 'e24216de8f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_entries_business_id'), 'pending_entries', ['business_id'], unique=False)
    # NOTE: autogenerate also detected drift on document_extractions'
    # unique-constraint-vs-unique-index representation and the embeddings
    # HNSW index unrelated to this change (pre-existing model/DB mismatch,
    # same drift noted in migrations 6930a3469643, 8c6fd7849c60, and
    # e24216de8f9c) -- deliberately not included; this migration only adds
    # pending_entries, per the additive-migration rule.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_entries_business_id'), table_name='pending_entries')
    op.drop_table('pending_entries')
    # ### end Alembic commands ###
