"""add whatsapp channel tables

Revision ID: 8c6fd7849c60
Revises: f10f9c18795a
Create Date: 2026-08-07 12:46:39.276827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8c6fd7849c60'
down_revision: Union[str, Sequence[str], None] = 'f10f9c18795a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_webhook_events_provider_external_id')
    )
    op.create_table('channel_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'external_id', name='uq_channel_identities_channel_external_id')
    )
    op.create_index(op.f('ix_channel_identities_business_id'), 'channel_identities', ['business_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_user_id'), 'channel_identities', ['user_id'], unique=False)
    op.create_table('channel_link_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_link_codes_business_id'), 'channel_link_codes', ['business_id'], unique=False)
    op.create_index(op.f('ix_channel_link_codes_code'), 'channel_link_codes', ['code'], unique=True)
    op.create_index(op.f('ix_channel_link_codes_user_id'), 'channel_link_codes', ['user_id'], unique=False)
    op.add_column('conversations', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('channel_identity_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_channel_identity_id'), 'conversations', ['channel_identity_id'], unique=False)
    # Named explicitly (autogenerate emitted None, i.e. "let Postgres pick a
    # name") -- op.drop_constraint needs a real name to target in
    # downgrade(), and this app declares no naming_convention on its
    # metadata for autogenerate to derive one from.
    op.create_foreign_key(
        'conversations_channel_identity_id_fkey', 'conversations', 'channel_identities', ['channel_identity_id'], ['id']
    )
    # NOTE: autogenerate also detected drift on document_extractions'
    # unique-constraint-vs-unique-index representation and the embeddings
    # HNSW index unrelated to this change (pre-existing model/DB mismatch,
    # same drift noted in migration 6930a3469643) -- deliberately not
    # included; this migration only adds the WhatsApp channel tables and
    # conversations' two new columns, per the additive-migration rule.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('conversations_channel_identity_id_fkey', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_channel_identity_id'), table_name='conversations')
    op.drop_column('conversations', 'channel_identity_id')
    op.drop_column('conversations', 'channel')
    op.drop_index(op.f('ix_channel_link_codes_user_id'), table_name='channel_link_codes')
    op.drop_index(op.f('ix_channel_link_codes_code'), table_name='channel_link_codes')
    op.drop_index(op.f('ix_channel_link_codes_business_id'), table_name='channel_link_codes')
    op.drop_table('channel_link_codes')
    op.drop_index(op.f('ix_channel_identities_user_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_business_id'), table_name='channel_identities')
    op.drop_table('channel_identities')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
