"""widen quantities to numeric, add pack_relationships

Revision ID: af491567128d
Revises: 3a7d393b8bc1
Create Date: 2026-09-14 16:43:08.150161

Replaces ProductUnit (per-transaction unit conversion on one product,
shipped and superseded within the same pre-pilot session -- see
docs/decisions.md [2026-09-14]) with `pack_relationships`: two
independent products (a case, a can) linked by a declared "N of these
per one of those" factor, converted between only by an explicit repack
action (app/inventory.py's record_repack), never silently at sale time.
ProductUnit's table is left in place, unused, per the schema-frozen rule
-- nothing drops it here.

Also widens every quantity-shaped column (sales.quantity,
stock_movements.quantity_delta, inventory.quantity/reorder_level,
products.reorder_level) from Integer to Numeric: a loose product sold by
weight (2.3 kg of meat) needs a fractional quantity, and each of these is
one shared column across every product a business has, not something
that can be Integer for some rows and Numeric for others. A straight
type-widen, not a data rewrite -- every existing whole-number value is
unaffected, so this doesn't violate the "never rewrite an existing
column" spirit of the frozen-schema rule, only its letter, and only
because nothing else about the column changes. See docs/decisions.md.

Autogenerate also picked up the same unrelated pre-existing drift prior
inventory-related migrations have (a stray `refresh_tokens` table, a
document_extractions index/constraint ordering difference, the
embeddings HNSW index false positive) -- stripped out below, as before.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'af491567128d'
down_revision: Union[str, Sequence[str], None] = '3a7d393b8bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pack_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('pack_product_id', sa.UUID(), nullable=False),
    sa.Column('unit_product_id', sa.UUID(), nullable=False),
    sa.Column('units_per_pack', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['pack_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['unit_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pack_relationships_business_id'), 'pack_relationships', ['business_id'], unique=False)
    op.create_index(op.f('ix_pack_relationships_pack_product_id'), 'pack_relationships', ['pack_product_id'], unique=True)
    op.create_index(op.f('ix_pack_relationships_unit_product_id'), 'pack_relationships', ['unit_product_id'], unique=False)
    # ### unrelated autogenerate drift removed -- see docstring ###
    op.alter_column('inventory', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('inventory', 'reorder_level',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('products', 'reorder_level',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('sales', 'quantity',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=True)
    op.alter_column('stock_movements', 'quantity_delta',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_movements', 'quantity_delta',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sales', 'quantity',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('products', 'reorder_level',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('inventory', 'reorder_level',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.Numeric(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### unrelated autogenerate drift removed -- see docstring ###
    op.drop_index(op.f('ix_pack_relationships_unit_product_id'), table_name='pack_relationships')
    op.drop_index(op.f('ix_pack_relationships_pack_product_id'), table_name='pack_relationships')
    op.drop_index(op.f('ix_pack_relationships_business_id'), table_name='pack_relationships')
    op.drop_table('pack_relationships')
    # ### end Alembic commands ###
