"""add whatsapp outbound messages and notification settings

Revision ID: e24216de8f9c
Revises: 8c6fd7849c60
Create Date: 2026-08-07 13:21:25.669058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e24216de8f9c'
down_revision: Union[str, Sequence[str], None] = '8c6fd7849c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('channel_identity_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('related_insight_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('send_method', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='queued', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['channel_identity_id'], ['channel_identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_messages_business_id'), 'outbound_messages', ['business_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_channel_identity_id'), 'outbound_messages', ['channel_identity_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_provider_message_id'), 'outbound_messages', ['provider_message_id'], unique=False)
    op.add_column('channel_identities', sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('channel_identities', sa.Column('notification_frequency', sa.String(), server_default='off', nullable=False))
    op.add_column('channel_identities', sa.Column('last_digest_sent_at', sa.DateTime(timezone=True), nullable=True))
    # NOTE: autogenerate also detected drift on document_extractions'
    # unique-constraint-vs-unique-index representation and the embeddings
    # HNSW index unrelated to this change (pre-existing model/DB mismatch,
    # same drift noted in migrations 6930a3469643 and 8c6fd7849c60) --
    # deliberately not included; this migration only adds outbound_messages
    # and channel_identities' three new columns, per the additive-migration
    # rule.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channel_identities', 'last_digest_sent_at')
    op.drop_column('channel_identities', 'notification_frequency')
    op.drop_column('channel_identities', 'last_inbound_at')
    op.drop_index(op.f('ix_outbound_messages_provider_message_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_channel_identity_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_business_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    # ### end Alembic commands ###
